[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "https://dieter.is/*"
to = "https://www.dieter.dev/"
status = 302
force = true

[[redirects]]
from = "https://dieterstinglhamber.me/"
to = "https://www.dieter.dev/"
status = 301
force = true

[[redirects]]
from = "https://dieterstinglhamber.me/about"
to = "https://www.dieter.dev/"
status = 301
force = true

[[redirects]]
from = "https://dieterstinglhamber.me/uses"
to = "https://www.dieter.dev/uses"
status = 301
force = true

[[redirects]]
from = "https://dieterstinglhamber.me/blog/*"
to = "https://www.dieter.dev/blog/:splat"
status = 301
force = true

[[redirects]]
from = "https://elhebert.be/*"
to = "https://www.dieter.dev/"
status = 302
force = true

[[redirects]]
from = "https://quirky-goldstine-861bee.netlify.app/*"
to = "https://www.dieter.dev/:splat"
status = 302
force = true
